---
- hosts: kubernetes-worker-nodes
  become: true
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=$HOME/join_token

  - name: Joining worker nodes with kubernetes master
    shell: "`grep -i 'kubeadm join' join_token`"

