---
- hosts: all
  become: true
  vars_files:
  - env_variables 
  tasks:
  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Installing required packages
    yum:
     name: "{{ item }}"
     state: present
    with_items: "{{ packages }}"

  - name: Starting and Enabling the required services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Allow Network Ports in Firewalld
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ ports }}"

  - name: create k8s.conf file
    file:
      path: /etc/sysctl.d/k8s.conf
      state: touch
      
  - name: Configuring Bridge Firewall Rule
    blockinfile:
      path: /etc/sysctl.d/k8s.conf
      block: | 
       net.bridge.bridge-nf-call-ip6tables = 1
       net.bridge.bridge-nf-call-iptables = 1

  - name: enabling bridge firewall rules
    shell: "{{ item }}"
    with_items: 
    - sysctl net.bridge.bridge-nf-call-iptables=1
    - sysctl net.ipv4.ip_forward=1
    - sysctl --system
    - echo "1" > /proc/sys/net/ipv4/ip_forward

  - name: restart systemd daemon
    systemd:
      daemon_reload: yes

  - name: restart required services
    service:
      name: "{{ item }}"
      state: restarted
    with_items: "{{ services }}"
